baseURL = 'https://www.pedaltheplanet.de/'
languageCode = 'de-de'  
title = 'Pedal the Planet'
description = 'Sabine und Thorsten auf Weltreise'
theme = ["hugo-shortcode-gallery"]
defaultContentLanguage = 'de'
timeout = '300s'
[services]
    [services.disqus]
        shortname = 'pedaltheplanet'
# menus = 'main'
[pagination]
    pagerSize = 6
[params]
    gallerySortOrder = 'asc'
    galleryRowHeight = '200'
    galleryMargins = '5'
    galleryThumbnailResizeOptions = '450x450 q90 Lanczos'
    galleryShowExif = true 
    galleryPreviewType = 'false'
    galleryEmbedPreview = 'true'
    galleryLastRow = 'left'